pitchtracker/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    url(r'^game/(?P<game_id>[^\s]+)', 'gameday.views.game_detail', name='game_detail'),
    url(r'^date/(?P<date>\d{2,}/\d{2,}/\d{4,})', 'gameday.views.game_day', name='game_day'),
    url(r'', 'gameday.views.game_day', {'date': None}, name='home'),
)

urlpatterns += staticfiles_urlpatterns()

gameday/models.py
from django.db import models
from django.db.models import Avg, Count, Max

EMPTY_PROPS = {"null": True, "blank": True}

LEAGUES = (
    ("AL", "American League"),
    ("NL", "National League")
)

class Player(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mlb_id = models.IntegerField(**EMPTY_PROPS)
    wins = ''
    losses = ''
    era = ''

    @property
    def image_url(self):
        return "http://mlb.mlb.com/images/gameday/mugshots/mlb/%s.jpg" % self.mlb_id

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

class Team(models.Model):
    name = models.CharField(max_length=100)
    abbreviation = models.CharField(max_length=6)
    league = models.CharField(max_length=2, blank=True, choices=LEAGUES)

    def __unicode__(self):
        return self.name

class Game(models.Model):
    date = models.DateField(db_index=True, **EMPTY_PROPS)
    start_time = models.CharField(max_length=20, blank=True)
    location = models.CharField(max_length=200, blank=True)
    home = models.ForeignKey(Team, related_name="home_games")
    away = models.ForeignKey(Team, related_name="away_games")
    mlb_id = models.CharField(max_length=255, db_index=True)

    def away_pitchers(self):
        return self._pitchers_by_side(self.away)

    def home_pitchers(self):
        return self._pitchers_by_side(self.home)
    
    def _pitchers_by_side(self, side):
        # TODO: has to be a better way to do this
        pitchers = Player.objects.filter(pk__in=
                self.at_bats.filter(pitcher_team=side, game=self).values_list(
                    "pitcher", flat=True).distinct()
            )
        for p in pitchers:
            p.average_speed = Pitch.objects.filter(at_bat__game=self,
                                    at_bat__pitcher=p).order_by().aggregate(speed=Avg('speed'))['speed']
            p.counts = Pitch.objects.filter(at_bat__game=self, at_bat__pitcher=p
                                               ).order_by().values('pitch_type').annotate(total=Count('pitch_type'))
        return pitchers

    def pitches_away(self):
        return Pitch.objects.filter(at_bat__hitter_team=self.home).order_by("at_bat", "id")

    def pitches_home(self):
        return Pitch.objects.filter(at_bat__hitter_team=self.away).order_by("at_bat", "id")

    def home_atbats(self):
        return self.hitter_atbats(self.home)

    def away_atbats(self):
        return self.hitter_atbats(self.away)

    def hitter_atbats(self, team):
        at_bats = []
        i = 0
        for ab in AtBat.objects.filter(game=self, hitter_team=team):
            if i < 9:
                at_bats.append([ab])
            else:
                at_bats[i % 9].append(ab)
            i += 1
        return at_bats

    @property
    def max_lineup_trips(self):
        result = AtBat.objects.filter(game=self).aggregate(times=Max("times_through_order"))
        if "times" in result:
            return max(1, result["times"])
        return 1

    def pitcher_stats_for_game(self, pitcher):
        pass

    def __unicode__(self):
        return "%s v. %s on %s" % (self.home.abbreviation,
                                   self.away.abbreviation, self.date.strftime("%m/%d/%Y"))

HANDS = (
    ("L", "L"),
    ("R", "R"),
)

class AtBat(models.Model):
    hitter = models.ForeignKey(Player, related_name="at_bats")
    hitter_team = models.ForeignKey(Team, related_name="hits")
    hitter_handed = models.CharField(max_length=1, choices=HANDS, db_index=True)
    pitcher = models.ForeignKey(Player, related_name="appearances")
    pitcher_team = models.ForeignKey(Team, related_name="pitches")
    game = models.ForeignKey(Game, related_name="at_bats")
    inning = models.SmallIntegerField(db_index=True)
    times_through_order = models.SmallIntegerField(db_index=True)
    result = models.CharField(max_length=2000)

    def __unicode__(self):
        return "%s hitting against %s, Inning #%d (%s)" % (self.hitter,
                                                           self.pitcher,
                                                           self.inning,
                                                           self.result)

    class Meta:
        ordering = ["id"]

class Pitch(models.Model):
    PITCH_TYPES = (
        ('FS', 'Splitter'),
        ('SL', 'Slider'),
        ('FF', '4-Seam Fastball'),
        ('FT', '2-Seam Fastball'),
        ('SI', 'Sinker'),
        ('CH', 'Change'),
        ('FA', 'Fastball'),
        ('CU', 'Curve'),
        ('FC', 'Cutter'),
        ('KN', 'Knuckle'),
        ('KC', 'Knuckle Curve'),
        ('XX', 'Unknown'),
    )
    EVENT_TYPES = (
        ('S', 'Strike'),
        ('B', 'Ball'),
        ('X', 'In Play')
    )
    at_bat = models.ForeignKey(AtBat, related_name="pitches")
    pitch_type = models.CharField(max_length=2, choices=PITCH_TYPES)
    description = models.CharField(max_length=500, blank=True)
    speed = models.FloatField(**EMPTY_PROPS)
    confidence = models.FloatField(**EMPTY_PROPS)
    nasty = models.FloatField(**EMPTY_PROPS)
    event_type = models.CharField(max_length=1, choices=EVENT_TYPES, blank=True)

    def __unicode__(self):
        return self.description

    class Meta:
        verbose_name_plural = "Pitches"
        ordering = ["at_bat", "id"]

gameday/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from .parser import GamedayParser

parser = GamedayParser()


#@cache_page(60*60)
def game_day(request, date):
    games = parser.get_games(date)
    return render(request, "index.html", {"games": games, "url": parser.current_url})


#@cache_page(5)
def game_detail(request, game_id):
    (game, home_pitchers, away_pitchers) = parser.get_game(game_id)
    if not game:
        return render(request, "no_game.html")
    return render(request, "game.html",
                  {"game": game, "url": parser.current_url,
                   "home_pitchers": home_pitchers,
                   "away_pitchers": away_pitchers,
                   "innings": range(1, 10),
                   "lineup_trips": range(1, game.max_lineup_trips + 1)})

templates/fragments/pitch_list.html
{% for ab in list %}
{% if forloop.first %}
<li class="batter">
  <header>
    <img src="{{ ab.hitter.image_url }}" />
    <hgroup>
      <h2>{{ ab.hitter }}</h2>
      <h3>v. {{ ab.pitcher }}</h3>
    </hgroup>
  </header>
{% endif %}
  <ol class="ab inning-{{ ab.inning }} trip-{{ ab.times_through_order }}">
  {% for p in ab.pitches.all %}
  <li class="pitch result-{{ p.event_type|lower }}" title="{{ p.description }}">
    {% if p.pitch_type %}<h4>{{ p.pitch_type }}</h4>{% endif %}
    {% if p.speed %}<span>{{ p.speed|floatformat:"0" }}</span>{% endif %}
</li>
  {% endfor %}
  </ol>
{% if forloop.last %}</li>{% endif %}
{% endfor %}

templates/fragments/pitchers.html
{% load gameday_tags %}
<li>
    <hgroup>
      <h2>{{ p }}</h2>
      <h3>SP</h3>
    </hgroup>
    
    {% if forloop.first %}
    <ul class="pitching-stats">
      <li>
        <h4>RECORD</h4>
        <p>{{ p.wins }} - {{ p.losses }}</p>
      </li>
      <li>
        <h4>ERA</h4>
        <p>{{ p.era }}</p>
      </li>
      <li>
        <h4>AVG</h4>
        <p><span class="avg-speed">{{ p.average_speed|floatformat:"1" }} mph</span></p>
      </li>
    </ul>
    
     <ul>
      {% for c in p.counts %}<li>{{ c.pitch_type|pretty_pitch }}: {{ c.total }}</li>{% endfor %}
    </ul>
    {% endif %}
</li>

templates/game.html
{% extends "layout.html" %}
{% load gameday_tags %}

{% block body %}

<header class="game">
  <h1><a href="#" class="home">{{ game.home }}</a> v. <a href="#" class="away">{{ game.away }}</a></h1>
  <h2>{{ game.location }}, {{ game.start_time }} ET</h2>
  <a href="/" class="today">Today</a>
  <form>
    <select id="id_lineup_trip" name="lineup_trip">
        <option value="">Trip through lineup</option>
        {% for t in lineup_trips %}<option value="{{ t }}">{{ t }}</option>{% endfor %}
    </select>
    <select id="id_inning" name="inning">
        <option value="">Inning</option>
        {% for i in innings %}<option value="{{ i }}">{{ i }}</option>{% endfor %}
    </select>
  </form>
</header>


<section class="team home" id="home-at-bats">
  <section class="pitchers">
    <ul>
      {% for p in away_pitchers %}{% include "fragments/pitchers.html" %}{% endfor %}
    </ul>
  </section>

  <section class="pitches frame">
    <ol class="slidee">
      {% for list in game.home_atbats %}{% include "fragments/pitch_list.html" %}{% endfor %}
    </ol>
  </section>
</section>

<section class="team away" id="away-at-bats">
  <section class="pitchers">
    <ul>
      {% for p in home_pitchers %}{% include "fragments/pitchers.html" %}{% endfor %}
    </ul>
  </section>

  <section class="pitches frame">
    <ol class="slidee">
      {% for list in game.away_atbats %}{% include "fragments/pitch_list.html" %}{% endfor %}
    </ol>
  </section>
{% endblock %}

{% block extra_js %}<script type="text/javascript">
var all_pitches, all_abs, all_batters;

$(document).ready(function () {
    $("#id_inning").change(show_inning);
    $("#id_lineup_trip").change(show_lineup_trip);
    all_pitches = $("li.pitch");
    all_abs = $("ol.ab");
    all_batters = $("li.batter")
});

// TODO: these should show the pitcher at the time and avg speed during
// the filtered period. Would be nice to update pitch counts as well
function show_inning(e)
{
    var inning = $(this).val();
    if (!inning)
    {
        return;
    }
    $("#id_lineup_trip").val("");
    all_batters.fadeOut();
    all_abs.hide();
    all_abs.filter(".inning-" + inning).show();
    all_batters.has("ol.inning-" + inning).fadeIn();
}

function show_lineup_trip(e)
{
    var trip = $(this).val();
    if (!trip)
    {
        return;
    }
    $("#id_inning").val("");
    all_batters.fadeOut();
    all_abs.hide();
    all_abs.filter(".trip-" + trip).show();
    all_batters.has("ol.trip-" + trip).fadeIn();
}
</script>{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
  <section class="todays-games">
    <h1>Today&rsquo;s Games</h1>
    <ul>
      {% for g in games %}
        <li>
        {% if g.playing %}
            <a href="/game/{{ g.mlburl }}">{{ g.away }} v {{ g.home }}</a>
            ({{ g.score }}){% if g.over %} F{% endif %}
        {% else %}
            {{ g.away }} v {{ g.home }}
        {% endif %}
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html lang="en">
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Pitch Tracker</title>
    <meta name="description" content="">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width">
    <meta name="google" value="notranslate" />
    <link href="{{ STATIC_URL }}style.css" rel="stylesheet" media="screen" type="text/css" />
  </head>
  <body>
    <section>
      {% block body %}{% endblock %}
    </section>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}sly.min.js"></script>
    {% block extra_js %}{% endblock %}
    <script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-39855669-1', 'localnine.com'); ga('send', 'pageview');
    </script>
  </body>
</html>

templates/no_game.html
{% extends "layout.html" %}

{% block body %}
  <section class="todays-games">
    <h1>Not Ready Yet</h1>
    <p>Sorry, this game doesn't seem to have started.</p>
  </section>
{% endblock %}